### ISSUE TITLE
Color Codes not working properly

### ISSUE THREAD

**Issue by AudricXDlmao** [projectcomet64/M64MM#33]
hello, i installed the movie maker alpha 6 today and when i put in a color code, it didn't work properly, it merged with the default color code and just became a mess, please help me.
![beeg beeg problem](https://user-images.githubusercontent.com/89954482/131770888-0e70a397-4876-43b9-82f6-aa9015c4a449.png)

**Comment by GlitchyPSIX** [comment]
I will assume you are using Project64 3.0 with the GLideN64 it includes.
You can done one of two things to fix this:
* Use GLideN64 4.0 instead of the version PJ643.0 comes with (download [here](https://github.com/gonetz/GLideN64/releases/tag/Public_Release_4_0))
* Follow the steps in [this video](https://www.youtube.com/watch?v=38Gi6KvbVcE)

**Comment by GlitchyPSIX** [comment]
I will assume you have fixed your problem. If there's any issue, feel free to reopen.

**Comment by AudricXDlmao** [comment]
wow thanks a bunch :))
